language: node_js

node_js:
    - "6"

install:
    - npm install

script:
    # - mocha --recursive ./dist/test/
    - npm run build
    - npm run cover

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

