language: node_js

environment:
    nodejs_version: "6"

branches:
    # whitelist
    only:
        - master

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install
    - npm install -g typescript

script:
    # - mocha --recursive ./dist/test/
    - npm run build
    - npm run cover

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

