
language: node_js

node_js:
    - lts/*

install:
    - npm install
    - npm install -g typescript
    - npm install -g codeclimate-test-reporter

script:
    - npm run build
    - npm run testonce
    - npm run cover
    # - mocha --recursive ./dist/test/

after_script:
    codeclimate-test-reporter < coverage/lcov.info
    "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
