export const MILLIS_PER_SECOND = 1000;
export const MILLIS_PER_MINUTE = MILLIS_PER_SECOND * 60;
export const MILLIS_PER_HOUR = MILLIS_PER_MINUTE * 60;
export const MILLIS_PER_DAY = MILLIS_PER_HOUR * 24;
